### ISSUE TITLE
전체 다운로드가 되지 않았는데 다운로드가 완료되었다는 알림이 뜹니다.

### ISSUE THREAD

**Issue by waffleplain** [box-archived/vlive-backup-bot#6]
전체 다운로드는 546개인데

대략 50개남짓 다운로드 된 후 전체 다운로드가 완료되었다는 알림이 뜹니다.

**Comment by box-archived** [comment]
종속 라이브러리의 문제로 확인됨.
[v0.0.6](https://github.com/box-archived/vlive-backup-bot/releases/tag/v0.0.6) 에서 해결되었습니다.
