### ISSUE TITLE
MAC OS 터미널 오류

### ISSUE THREAD

**Issue by waffleplain** [box-archived/vlive-backup-bot#7]
![image](https://user-images.githubusercontent.com/76877472/112440064-37bd7380-8d8d-11eb-8eaf-fa357a505ceb.png)

터미널 실행 후

sh (스페이스바) run.sh 드래그앤드랍 하면 위와 같이 뜬다고 합니다.

**Comment by box-archived** [comment]
[v0.0.7](https://github.com/box-archived/vlive-backup-bot/releases/tag/v0.0.7) 릴리즈에서 해결되었습니다.
